# Generated by Django 5.2.8 on 2025-12-02 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ListeEleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='liste/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Listes des élèves',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('code_eleve', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Code élève')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('nb_retard', models.IntegerField(default=0, verbose_name='Retards')),
                ('nb_absence', models.IntegerField(default=0, verbose_name='Absences')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Inter 1')),
                ('inter2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Inter 2')),
                ('inter3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Inter 3')),
                ('inter4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Inter 4')),
                ('devoir1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Devoir 1')),
                ('devoir2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Devoir 2')),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleves')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.semestre')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'unique_together': {('eleve', 'matiere', 'semestre')},
            },
        ),
    ]
