# Generated by Django 5.2.4 on 2025-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_eleve', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=20)),
                ('nb_retard', models.IntegerField(default=0)),
                ('nb_absence', models.IntegerField(default=0)),
            ],
        ),
    ]
