# Generated by Django 5.2.4 on 2025-11-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('S1', '1er Semestre'), ('S2', '2ème Semestre')], max_length=2)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
            ],
            options={
                'unique_together': {('nom', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('appreciation', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleves')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.semestre')),
            ],
            options={
                'unique_together': {('eleve', 'matiere', 'semestre')},
            },
        ),
    ]
