# Generated by Django 5.2.4 on 2025-11-18 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_matiere_semestre_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleves',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom'], 'verbose_name': 'Matière'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Bulletin de notes'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='devoir1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='note',
            name='devoir2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='note',
            name='inter1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='note',
            name='inter2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='note',
            name='inter3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='note',
            name='inter4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='code_eleve',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code élève'),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='nb_absence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='nb_retard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='appreciation',
            field=models.TextField(blank=True, verbose_name='Appréciation du professeur'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='annee_scolaire',
            field=models.CharField(default='2025-2026', max_length=9),
        ),
    ]
