# Generated by Django 5.2.4 on 2025-11-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('classe_concernee', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parent', models.CharField(blank=True, max_length=50)),
                ('commentaire', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='avis.avis')),
            ],
            options={
                'ordering': ['date_publication'],
            },
        ),
    ]
