MATIERES_PAR_CLASSE = {
    "2NDE IMI": ["FRANÇAIS", "ANGLAIS", "MATH", "EB", "LA", "AS", "SEV", "SER", "ALGO", "MATH APPLIQUE", "LEGIS"],
    "2NDE F3": ["FRANÇAIS", "ANGLAIS", "MATH", "PCT", "TECHNO", "SCHÉMA", "DESSIN", "ELECTRO", "PRATIQUE", "MEL"],
    "TLE F3": ["FRANÇAIS", "ANGLAIS", "MATH", "PHYSIQUE", "ELECTRO", "EST", "PRATIQUE", "MEL", "DESSIN", "ANGLAIS"],
    "TLE IMI": ["FRANÇAIS", "ANGLAIS", "MATH", "EB", "RESEAU", "RP", "MATH APPLIQUÉ", "LEGIS", "BD", "PG", "ELEC"],
    "2NDE F4": ["FRANÇAIS", "ANGLAIS", "MATH", "PHYSIQUE", "DESSIN", "INFORMATIQUE", "TM/TC", "TP", "MECANIQUE", "PREVENTION", "LEGIS"],
    "1ERE F4": ["FRANÇAIS", "ANGLAIS", "MATH", "PCT", "RDM", "PE", "DESSIN", "SMC", "TP", "METRE", "HYGIENE", "PC"],
    "TLE F4": ["FRANÇAIS", "ANGLAIS", "MATH", "PCT", "RDM", "PE", "DESSIN", "METRE", "PC", "BA", "TP", "LEGIS"],
    "2NDE FC": ["FRANÇAIS", "ANGLAIS", "MATH", "EPS", "PHYSIQUE", "HIST-GEO", "PHYSIQUE APPLIQUE", "AUTOMATISME", "DESSIN", "ELECTRO DE BASE"],
    "1ERE HR": ["FRANÇAIS", "ANGLAIS", "MATH", "TC", "SAAH", "ECONOMAT", "TRB", "DROIT", "MERCATIQUE", "COMPTABILITE"],
}