# Generated by Django 5.2.4 on 2025-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_evenement', models.CharField(choices=[('vacances', 'Vacances'), ('examen', 'Examens'), ('reunion', 'Reunions'), ('autre', 'Autres')], max_length=20)),
            ],
        ),
    ]
